### PR TITLE
ci: Add GitHub Workflow

### PR DESCRIPTION
**Pull request by seanpoulter**
### Proposed Changes

Add GitHub Workflow

* Remove **.travis.yml**
* Use Node v14 because chromedriver` needs >=14.
* Use Chrome and ChromeDriver already available on the GitHub Runner ([docs](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#browsers-and-drivers)).
* Override the path to ChromeDriver using the same environment variable as [webdriverio/webdriverio#12338](https://github.com/webdriverio/webdriverio/pull/12338/files#diff-040f5b411a167ce7cb8c588dd6ba749a36d0173c8efa46a75b4c971e45d9e72bR76)

### Notes

* What do you want to do about the test coverage without CoverAlls?

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
🙌 Awesome!

**Comment by christian-bromann** [comment]
> * What do you want to do about the test coverage without CoverAlls?

Let's remove it.

**Comment by seanpoulter** [comment]
> > * What do you want to do about the test coverage without CoverAlls?
> 
> Let's remove it.

**Done**

**Comment by christian-bromann** [comment]
@seanpoulter you should have access now, can you confirm?

**Comment by christian-bromann** [comment]
> We can probably leave it since we won't touch the repo much after the Dependabot change, or updating the tests, right? 🤷

I have no plans to develop this project further given our progress in v9 in Shadow DOM peircing.

**Pull request merged**
