### PR TITLE
[Experimental] Puppeteer Custom Engine support

### PR DESCRIPTION
**Pull request by Georgegriff**
https://github.com/puppeteer/puppeteer/issues/5405

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
@Georgegriff any plans to release this as an experimental option? I copied the changes manually now :)

One suggestion regarding the name, I think something like `deep` or `pierce-shadow` would be a bit more descriptive.

**Comment by Georgegriff** [comment]
I was waiting for it to land in stable puppeteer but I'm open to shipping a version the experience apis.

Yeah the name is tricky I could make the name customisable, potentially, I'll look into it

**Comment by LarsDenBakker** [comment]
I'm not sure how long puppeteer plans to have this be experimental, but I think it would be great to offer this option in the meantime. I need it for a project myself, but we should promote this library more in general!

**Comment by Georgegriff** [comment]
Released under 0.6.1 as experimental feature https://github.com/Georgegriff/query-selector-shadow-dom/releases/tag/0.6.1

**Pull request merged**
